# Generated by Django 4.2.7 on 2025-11-05 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部署', 'verbose_name_plural': '部署一覧'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'verbose_name': '通知ログ', 'verbose_name_plural': '通知ログ'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員一覧'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'システム設定', 'verbose_name_plural': 'システム設定'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': '来訪', 'verbose_name_plural': '来訪記録'},
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('headquarters', '本部'), ('department', '部'), ('section', '課'), ('special', '例外部門')], max_length=20, verbose_name='部署タイプ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.department', verbose_name='親部署'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='escalation_level',
            field=models.IntegerField(default=0, verbose_name='エスカレーションレベル'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(max_length=50, verbose_name='通知タイプ'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.visit', verbose_name='来訪'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='氏名（カナ）'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='写真URL'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='substitute1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='api.staff', verbose_name='代理1'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='substitute2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for', to='api.staff', verbose_name='代理2'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='キー'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(verbose_name='値'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='escalation_level',
            field=models.IntegerField(default=0, verbose_name='エスカレーションレベル'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notified_staff',
            field=models.ManyToManyField(blank=True, related_name='notified_visits', to='api.staff', verbose_name='通知対象スタッフ'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='来訪目的'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='目的タイプ'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='response_message',
            field=models.TextField(blank=True, verbose_name='対応メッセージ'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='対応時間'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', '待機中'), ('notified', '通知済み'), ('accepted', '対応中'), ('completed', '完了'), ('cancelled', 'キャンセル'), ('unavailable', '不在')], default='waiting', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('appointment', 'アポイントあり'), ('no-appointment', 'アポイントなし'), ('delivery', '宅配業者')], max_length=20, verbose_name='来訪種別'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='来訪日時'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor_company',
            field=models.CharField(max_length=200, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor_name',
            field=models.CharField(max_length=100, verbose_name='来訪者名'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='api_department',
        ),
    ]
