# Generated by Django 4.2.7 on 2025-11-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='background_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='背景画像URL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='社員画像'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', '待機中'), ('notified', '通知済み'), ('accepted', '対応中'), ('completed', '完了'), ('cancelled', 'キャンセル'), ('unavailable', '不在')], default='', max_length=20, verbose_name='状態'),
        ),
    ]
