# Generated by Django 4.2.7 on 2025-11-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemsetting_background_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
