# Generated by Django 4.2.7 on 2025-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_staff_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='背景画像ファイル'),
        ),
    ]
