# Generated by Django 4.2.7 on 2025-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemsetting_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='substitute1',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='substitute2',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='background_image_url',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='写真URL'),
        ),
    ]
