# Generated by Django 4.2.7 on 2025-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_staff_is_active_remove_staff_substitute1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='purpose_custom',
            field=models.TextField(blank=True, verbose_name='用件（自由入力）'),
        ),
        migrations.AddField(
            model_name='visit',
            name='purpose_preset',
            field=models.CharField(blank=True, max_length=200, verbose_name='用件（選択肢）'),
        ),
    ]
