# Generated by Django 4.2.7 on 2025-11-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visit_purpose_custom_visit_purpose_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='status',
        ),
    ]
