# Generated by Django 4.2.7 on 2025-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', '担当者応答待ち'), ('completed', '対応完了'), ('escalated', 'エスカレーション済み'), ('notified', '総務へ通知済み')], default='waiting', max_length=20, verbose_name='ステータス'),
        ),
    ]
