# Generated by Django 4.2.7 on 2025-11-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='purpose_custom',
            field=models.TextField(blank=True, null=True, verbose_name='用件（自由入力）'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose_preset',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用件（選択肢）'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', '担当者応答待ち'), ('manager', '担当者対応'), ('escalated', 'エスカレーション済み'), ('notified', '総務部対応')], default='waiting', max_length=20, verbose_name='ステータス'),
        ),
    ]
