# Generated by Django 4.2.7 on 2025-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_visit_purpose_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/staff_photos/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose_custom',
            field=models.TextField(blank=True, default='', verbose_name='用件（自由入力）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose_preset',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='用件（選択肢）'),
            preserve_default=False,
        ),
    ]
