# Generated by Django 4.2.7 on 2026-01-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_staff_photo_url_alter_visit_purpose_custom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
