# Generated by Django 4.2.7 on 2026-01-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='teams_api_url',
            field=models.URLField(blank=True, help_text='この部署に通知を飛ばすTeamsチャネルのAPI(Webhook) URLを入力してください', max_length=500, null=True, verbose_name='Teams API URL'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='写真'),
        ),
    ]
