# Generated by Django 4.2.7 on 2026-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_department_teams_api_url_alter_staff_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AlterField(
            model_name='department',
            name='teams_api_url',
            field=models.URLField(blank=True, help_text='この部署に通知を飛ばすTeamsチャネルのAPI URLを入力してください', max_length=500, null=True, verbose_name='Teams API URL'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', '担当者応答待ち'), ('manager', '担当者対応'), ('notified', '総務部対応')], default='waiting', max_length=20, verbose_name='ステータス'),
        ),
    ]
