# Generated by Django 4.2.7 on 2026-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_staff_email_remove_staff_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('headquarters', '本部'), ('section', '本部直下')], max_length=20, verbose_name='部署タイプ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属・役職'),
        ),
    ]
