# Generated by Django 4.2.7 on 2025-10-30 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
                ('department_type', models.CharField(choices=[('headquarters', '本部'), ('department', '部'), ('section', '課'), ('special', '例外部門')], max_length=20, verbose_name='部署タイプ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.department', verbose_name='親部署')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署一覧',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='社員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='氏名（カナ）')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('photo_url', models.URLField(blank=True, verbose_name='写真URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.department', verbose_name='部署')),
                ('substitute1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='frontend.staff', verbose_name='代理1')),
                ('substitute2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for', to='frontend.staff', verbose_name='代理2')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員一覧',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='キー')),
                ('value', models.TextField(verbose_name='値')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('appointment', 'アポイントあり'), ('no-appointment', 'アポイントなし'), ('delivery', '宅配業者')], max_length=20, verbose_name='来訪種別')),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('notified', '通知済み'), ('accepted', '対応中'), ('completed', '完了'), ('cancelled', 'キャンセル'), ('unavailable', '不在')], default='waiting', max_length=20, verbose_name='状態')),
                ('visitor_company', models.CharField(max_length=200, verbose_name='会社名')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='来訪者名')),
                ('purpose', models.TextField(blank=True, verbose_name='来訪目的')),
                ('purpose_type', models.CharField(blank=True, max_length=100, verbose_name='目的タイプ')),
                ('response_message', models.TextField(blank=True, verbose_name='対応メッセージ')),
                ('response_time', models.DateTimeField(blank=True, null=True, verbose_name='対応時間')),
                ('escalation_level', models.IntegerField(default=0, verbose_name='エスカレーションレベル')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='来訪日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('notified_staff', models.ManyToManyField(blank=True, related_name='notified_visits', to='frontend.staff', verbose_name='通知対象スタッフ')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.staff', verbose_name='担当者')),
            ],
            options={
                'verbose_name': '来訪',
                'verbose_name_plural': '来訪記録',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50, verbose_name='通知タイプ')),
                ('escalation_level', models.IntegerField(default=0, verbose_name='エスカレーションレベル')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.staff', verbose_name='担当者')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='frontend.visit', verbose_name='来訪')),
            ],
            options={
                'verbose_name': '通知ログ',
                'verbose_name_plural': '通知ログ',
            },
        ),
    ]
