# Generated by Django 4.2.7 on 2025-10-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='substitute1',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='substitute2',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='notified_staff',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
